[package]
name = "masonry-layout-helper"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
ciborium = "0.2.1"
serde = "1.0"
wasm-minimal-protocol = "0.1.0"

[profile.release]
lto = true
strip = true
opt-level = 'z'
codegen-units = 1
panic = 'abort'

[workspace]
